sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx4677c6d41a7486ad
    secret: 6cc818a972c0cd23b7da91a468ff97a0
